// What the pager says when you open the app. Silly and 90s, in the voice of a pager.
export const GREETINGS = [
  "BEEP!!",
  "BEEP BEEP!",
  "BEEEEEEP!",
  "May the force be with you",
  "Howdy!",
  "Page me maybe?",
  "143!",
  "07734",
  "Cowabunga!",
  "Radical!",
  "Totally tubular!",
  "Gnarly, dude!",
  "All that and a bag of chips",
  "Talk to the hand",
  "Don't have a cow",
  "As if!",
  "Whatever!",
  "Booyah!",
  "Word up!",
  "Dial-up not required",
  "You've got Pages!",
  "Call me back ASAP!",
  "Clipped to your belt",
  "Please hold… just kidding",
  "Is this thing on?",
  "Boop!",
  "Y2K ready!",
  "Doctor on call!",
  "Beep me if you wanna reach me",
  "Stay tuned, dude",
  "Rewinding your messages…",
  "Insert quarter for more pages",
  "Hang loose!",
  "Hello, 1997!",
  "Low battery? Nah.",
  "Mission accomplished: you showed up",
  "Pagers assemble!",
  "Ring ring, I mean beep beep",
  "Not a toaster",
  "Out of range? Never!",
  "You rang?",
  "Ahoy, matey!",
  "Beep boop, human",
  "Roger that!",
  "10-4, good buddy",
  "Wassup?!"
];

export const pickGreeting = (rand: () => number = Math.random) => GREETINGS[Math.floor(rand() * GREETINGS.length)];
